#!/usr/bin/env ruby

require "rspec_logfmt_formatter"

file = ARGV.first
out = -> { file ? File.new(file, "w") : $stdout }

ARGF.read
  .then { |input| RspecLogfmtFormatter.collate input }
  .then { |collated| out.call.puts collated }
